groups:
  - name: system_alerts
    interval: 15s
    rules:
      - alert: HighCPU
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 75
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "CPU usage > 90%"
          description: "CPU usage is above 75% for more than 1 minute."

      - alert: HighRAM
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 90
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "RAM usage > 90%"
          description: "RAM usage above 90% for more than 1 minute."

      - alert: DiskFull
        expr: (node_filesystem_size_bytes{fstype!~"tmpfs|overlay"} - node_filesystem_free_bytes{fstype!~"tmpfs|overlay"}) / node_filesystem_size_bytes{fstype!~"tmpfs|overlay"} * 100 > 80
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Disk usage > 80%"
          description: "Disk usage is above 80% for more than 1 minute."

      - alert: ContainerDown
        expr: time() - container_last_seen > 60
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Container {{ $labels.name }} is down"
          description: "A container has not been seen for over 60 seconds."
