services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - "--config.file=/docker-lab/config/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    volumes:
      - ../config/prometheus/prometheus.yml:/docker-lab/config/prometheus/prometheus.yml:ro
      - ../config/prometheus/alerts.yml:/docker-lab/config/prometheus/alerts.yml:ro
      - ../data/prometheus:/prometheus
    restart: unless-stopped
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    networks:
      - monitoring
    restart: unless-stopped
    pid: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ../data/grafana:/var/lib/grafana
    networks:
      - frontend
      - monitoring
    restart: unless-stopped

  loki:
    image: grafana/loki:2.9.8
    container_name: loki
    volumes:
      - ../config/loki/loki.yml:/etc/loki/loki.yml:ro
      - ../data/loki:/loki
    command: -config.file=/etc/loki/loki.yml
    networks:
      - monitoring
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ../config/promtail/promtail.yml:/etc/promtail/promtail.yml:ro
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/promtail.yml
             -config.expand-env=true
    networks:
      - monitoring
    restart: unless-stopped

  crm-db:
    image: mariadb:10.5
    container_name: crm-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: espocrm
      MYSQL_USER: espouser
      MYSQL_PASSWORD: espopass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  crm:
    image: espocrm/espocrm
    container_name: crm-app
    restart: always
    ports:
      - "3005:80"
    environment:
      ESPOCRM_DATABASE_HOST: crm-db
      ESPOCRM_DATABASE_USER: espouser
      ESPOCRM_DATABASE_PASSWORD: espopass
      ESPOCRM_DATABASE_NAME: espocrm
    depends_on:
      - crm-db
    volumes:
      - crm:/var/www/html
    networks:
      - frontend
      - backend

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    networks:
      - monitoring

networks:
  frontend:
    external: true
  backend:
    internal: true
  monitoring:
    internal: true

volumes:
  db_data:
  crm:
